version: '2'

services:

  aerospike:
    container_name: aerospike
    image: aerospike/aerospike-server
    ports:
      - 3000:3000
      - 3001:3001
      - 3002:3002
      - 3003:3003
    volumes:
      - ./aerospike/etc:/opt/aerospike/etc
      - ./aerospike/data:/opt/aerospike/data
