apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app }}-svc
spec:
  ports:
    - port: {{ .Values.service.externalPort }}
      targetPort: {{ .Values.service.internalPort }}
  selector:
    component: {{ .Values.app }}-web
